command -nargs=* Gc call Vitter#GitCheckout(<f-args>)
command -nargs=* Gb call Vitter#GitBranchs(<f-args>)
command -nargs=* Gl call Vitter#GitLog(<f-args>)
command -nargs=* Gd call Vitter#GitDiff(<f-args>)
command -nargs=* Gr call Vitter#GitRebase(<f-args>)
command -nargs=* Gf call Vitter#GitFetch(<f-args>)
command Gcf call Vitter#GitCheckoutThisFIle()
